### ISSUE TITLE
How can I input multiple images? 

### ISSUE THREAD

**Issue by qishisuren123** [RunpeiDong/DreamLLM#13]
I tried modifying the `vqa_inference.py` file to allow input of multiple images, but the model seems to only recognize the first image. Is there an example of code that supports inputting multiple images?

**Comment by RunpeiDong** [comment]
Hi @qishisuren123,

Of course, you should try to modify the script by setting the inputs as a loop of image inputs. Then, the model will take all images as inputs one by one.

**Comment by RunpeiDong** [comment]
Hi @qishisuren123,

Does my answer address your question? Do you need further help?
