### ISSUE TITLE
transformers version error 

### ISSUE THREAD

**Issue by pzwstudy** [RunpeiDong/DreamLLM#17]
when l use transformers==4.35.2, l get a error when l load local model ' stabilityai/stable-diffusion-2-1-base does not appear to have a file named config.json.',l can load 'project/DreamLLM/dreamllm-7b-chat-aesthetic-v1.0';after l upgrade transformers ==4.40.2,l can get load 'stable-diffusion-2-1-base ',but l can not load local '/mnt/data/home/usera6k04/project/DreamLLM/dreamllm-7b-chat-aesthetic-v1.0'
![QQ截图20240514204930](https://github.com/RunpeiDong/DreamLLM/assets/107555161/ef245be2-9ed6-4515-b661-915c3ee5f15e)

**Comment by RunpeiDong** [comment]
Hi @pzwstudy,

It is weird. I suggest that you first download all models on your local disk, then load all models from your local disk by setting the path and `local_files_only=True`. 4.35.2 should be fine, and I have not tried 4.40.2 before, there may be some problems when you upgrade the `transformers` version. The `transformers` team is rapidly and actively upgrading the package with large changes.

**Comment by pzwstudy** [comment]
Thanks,when I execute the `DreamLLM/projects/dreamllm/inference.py`,l conform an error `Segmentation fault      (core dumped) python ./inference.py`,how can I fix it?

**Comment by RunpeiDong** [comment]
Hi @pzwstudy,

I cannot infer the exact problem you met from the segmentation fault error. This should not happen as expected. Can you provide more information so that I can help you?

Best,
Runpei

**Comment by RunpeiDong** [comment]
Hi @pzwstudy,

Have you addressed your problem? Do you need further help?

Best,
Runpei

**Comment by pzwstudy** [comment]
solved!
thanks for your reply ,if I have any other problem,I will ask you for help

**Comment by RunpeiDong** [comment]
Problem solved. The issue is closed, but any questions can be brought up later.
