### ISSUE TITLE
Looking forward to the code

### ISSUE THREAD

**Issue by shileims** [RunpeiDong/DreamLLM#2]
Hi Author,
    Thanks for the excellent work. Looking forward to the code. Thanks

**Comment by PHOENIXFURY007** [comment]
Any dates by when the code will be released?

**Comment by RunpeiDong** [comment]
Thanks for your interest in our work. We are currently working on code cleaning and in progress of DreamLLM v2, which will be empowered with more interesting capabilities. All codes, models, and demos will be released in the next one or two months after the paper reviews are out.

**Comment by hdjsjyl** [comment]
@RunpeiDong , do you have any updates about code publish? Thanks

**Comment by haochuan-li** [comment]
Really solid work! Any update about code release date?

**Comment by RunpeiDong** [comment]
Sorry for the delay. I was busy with my PhD application. The code is released now.

We release the codebase Omni, a general toolkit for developing multimodal LLMs.
