### ISSUE TITLE
Dream start token

### ISSUE THREAD

**Issue by yeongjoonJu** [RunpeiDong/DreamLLM#20]
First of all, thank you for sharing your excellent work.

I'm trying to implement the examples provided in your paper.
Distinct works, such as Image-to-Text and Text-to-Image, were implemented well.

Similar to the following example in your project page:

![image](https://github.com/RunpeiDong/DreamLLM/assets/30193942/394f4c63-52b5-493f-ae41-5ffbf251f7a4)

I tried the following code to reproduce the example manually:

```python
from PIL import Image
from transformers import CLIPImageProcessor
from omni.utils.conversation import KeywordsStoppingCriteria, SeparatorStyle, default_conversation
from omni.constants import (
    DEFAULT_IMAGE_END_TOKEN,
    DEFAULT_IMAGE_PATCH_TOKEN,
    DEFAULT_IMAGE_START_TOKEN,
    DEFAULT_DREAM_START_TOKEN,
    MODEL_ZOOS,
)
image_token_len = 256
# prompt = "please provide an accurate and concise description of the given image."
prompt = "Can you give a short introduction to this movie?"
system_prompt = ""
post_prompt = '"spider-man: no way home" is an upcoming superhero movie featuring the marvel comics character spider-man. in the image, spider-man is seen in action, leaping into the air while wearing his red and blue suit. the movie is the sequel to "spider-man: far from home" and is set to continue the adventures of peter parker as he balances his life as a high school student and his role as spider-man.'
path = MODEL_ZOOS["openai/clip-vit-large-patch14"]
image_processor = CLIPImageProcessor.from_pretrained(path, local_files_only=False)
qs = (
    system_prompt
    + DEFAULT_IMAGE_START_TOKEN
    + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
    + DEFAULT_IMAGE_END_TOKEN
    + prompt
)

conv = default_conversation.copy()
conv.append_message(conv.roles[0], qs)
conv.append_message(conv.roles[1], post_prompt)
conv.append_message(conv.roles[0], "Good. Show me an illustration of a panda wearing a suit and posing like the spider-man.")
conv.append_message(conv.roles[1], "")

image = Image.open("spiderman.jpg") #images[0]

image_tensor = get_img_tensor(image, image_processor)

stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
prompt = conv.get_prompt()
if prompt.endswith(stop_str):
    prompt = prompt[: -len(stop_str)]

inputs = tokenizer([prompt])

input_ids = torch.as_tensor(inputs.input_ids).cuda()

keywords = [stop_str]
stopping_criteria = KeywordsStoppingCriteria(keywords, tokenizer, input_ids)

with torch.autocast("cuda", dtype=torch.bfloat16):
    output_ids = model.generate(
        input_ids,
        images=image_tensor.unsqueeze(0).half().cuda(),
        do_sample=True,
        temperature=0.2,
        max_new_tokens=1024,
        stopping_criteria=[stopping_criteria],
    )
    
input_token_len = input_ids.shape[1]
n_diff_input_output = (input_ids != output_ids[:, :input_token_len]).sum().item()
if n_diff_input_output > 0:
    print(f"[Warning] {n_diff_input_output} output_ids are not the same as the input_ids")
outputs = tokenizer.batch_decode(output_ids[:, input_token_len:], skip_special_tokens=True)[0]
outputs = outputs.strip()
if outputs.endswith(stop_str):
    outputs = outputs[: -len(stop_str)]
outputs = outputs.strip()
outputs = outputs.capitalize()

print(outputs)
```

I got the following result.

**Output**
```
I'm sorry, but i cannot provide an illustration of a panda wearing a suit and posing like spider-man, as it is not a realistic scenario. pandas are not known to wear suits or pose like superheroes. however, if you would like to see a panda in a more natural setting, i can provide an image of a panda in its natural habitat.
```

I expected an output `DEFAULT_DREAM_START_TOKEN`. But I got a text like a style of alpaca training data.

Additionally, a prompt to create an image was also attempted, but the result was as follows:

**Input prompt**
```
Show me a photo of a cat.
```

**Output**
```
Certainly! here's a photo of a cat.
```

I found a code that conditions `dream_query` as follows:

`DreamLLMForCausalLLM` in `omni/models/dreamllm/modeling_dreamllm.py`
```python
def get_prompt_embeds(
        self,
        tokenizer: PreTrainedTokenizerBase,
        prompt: str | list[str] | MultimodalContent,
        device: str | torch.device,
    ):
    ...
    dream_query = self.model.prepare_dream_queries_with_special_token(batch_size=batch_size)
```

And this function is used in a function `encode_prompt`. However, I found that this function is used only in the image generation process.

If what I understand is correct, should DREAM_START_TOKEN only be put manually?

If you can help me reproduce "Free-form Interleaved Document Creation", I would greatly appreciate it.

I'm looking forward to your reply!

**Comment by RunpeiDong** [comment]
Your script cannot do this because you haven't done it right. See https://github.com/RunpeiDong/DreamLLM/issues/9#issuecomment-2046540819.

As I have stated, you have to detect the model's output, and when the model outputs a `dream_start` token, you should then apply diffusion_pipline. So, remember this: you should write a script that keeps monitoring the output token; if it is a `dream_start` token, apply diffusion pipeline. Then, don't forget to put the image as input back to the model for the following content. Until a stop token is generated, the process should be repeated. I haven't found time to write this script recently, I hope this information can help you.

**Comment by yeongjoonJu** [comment]
Thank you for your fast response.

I'll try to implement the script based on your comments.

If my work is successful, I will close this issue after sharing the script.

Thank you!
