### ISSUE TITLE
Results Reproduction 

### ISSUE THREAD

**Issue by karrykkk** [RunpeiDong/DreamLLM#21]
Hi~Thanks for your great work!

Can you provide the `fid_stats_mscoco256_val.npz` to reproduce the COCO-30k FID reported in your paper? 

Thanks in advance! ☺️

**Comment by RunpeiDong** [comment]
Hi @karrykkk,

It's [here](https://drive.google.com/drive/folders/1wopXzbuu70hDSEgG7dzzUekurdxW-zFU). The instructions are written at [here](https://github.com/RunpeiDong/DreamLLM/blob/master/omni/eval/README.md#text2image). Please use [this model](https://huggingface.co/RunpeiDong/dreamllm-7b-chat-v1.0) and run 8/16 times with different seeds and best CLIP selection. The aesthetic one is fine-tuned on some JourneyDB images that are very different from COCO images. However, the aesthetic model is also trained on llava80k, so the comprehension performance is very strong.

**Comment by FolSpark** [comment]
> "The aesthetic one is fine-tuned on some JourneyDB images"

Did you only train dream query and projector when fine-tuning aesthetic models? Or did Unet train too?

**Comment by RunpeiDong** [comment]
The U-Net is kept frozen. However, during fine-tuning, the LLM will also be fine-tuned.
