### ISSUE TITLE
Question about train stage1

### ISSUE THREAD

**Issue by FolSpark** [RunpeiDong/DreamLLM#24]
I want to retrain dreamllm from scratch, but I meet many bugs.

1. I run the scripts in `run_stage1_comprehension_only.sh` ,I meet first bug:
![image](https://github.com/user-attachments/assets/ee9dfcd6-67cd-4a0d-9614-34289fad25e9)

this is because in `projects/dreamllm/configs/stage1/base.py` , line 18: 

![image](https://github.com/user-attachments/assets/1df12aeb-9797-4d92-a08c-5e4b1754122a)

I guess I should download the`lmsys/vicuna-7b-v1.1` manually from huggingface. I do it, and fix the `model_name_or_path` in line19. 

This bug is successfully fixed.

2. Then I meet another bug:

![image](https://github.com/user-attachments/assets/6f9d27e5-0e66-4b12-8a3d-758482862197)

I guess this occurs when load opanai.clip, bug why the `self.load_model(pretrained_model_name_or_path)` is the path I mentioned in Question1. Should It be `openai/clip-vit-large-patch14` in projects/dreamllm/configs/common.py: line 30?

The similar question issued in #22 , But I not find how to solve . Are you sure your Code for training is correct? How to fix this bug? 

Best

Guo

**Comment by RunpeiDong** [comment]
If you are using your local path, please specify `local_files_only` as `True`.

**Comment by RunpeiDong** [comment]
Besides, the local path should not be the directory. Instead, you should use the checkpoint directory, which is located inside the file directory.

**Comment by FolSpark** [comment]
Yes, I have noticed what you mentioned above, What I wonder is:
why the clip_vision_embedding 's config: `pretrained_model_name_or_path` is changed from `None`(it is in projects/dreamllm/configs/common.py: line:33) to `.../DreamLLM/huggingface_cache/hub/vicuna-7b-v1.1`(What I write on line19)? as the last error picture. 

Besides that, I didn't make any changes to the code.

**Comment by RunpeiDong** [comment]
It is `None` because in stage I you have to train it, right? When it is set as None, the vision encoder will load CLIP weights as default.

**Comment by FolSpark** [comment]
I know what you mean, but maybe you don't understand what I mean. I guess your code have a bug, I only start train stage 1 by annotating the line242,243, 400,401 in DreamLLM/omni/models/dreamllm/modeling_dreamllm.py. Is this a bug?

**Comment by RunpeiDong** [comment]
Sorry, I cannot provide help as sometimes bugs happen when people are running on different machines and environments. There are a lot of details to be known to check bugs, and I think such bugs can be easily fixed to fit your environment. The codes were checked before on my own environments and machines, and I have never heard the issue you mentioned from other users.
