### ISSUE TITLE
Where do the CIDEr scores on COCO come from?

### ISSUE THREAD

**Issue by XqZeppelinhead0702** [RunpeiDong/DreamLLM#25]
Hello, recently I've been working on image-captioning tasks and noticed that you reported CIDEr scores on COCO in your paper. In fact, I failed to find any golden annotations of COCO test set so I wonder how you get the CIDEr scores? Did you test the image-captioning task on dev set or use any official evaluation tool to obtain them? I would greatly appreciate it if you could provide a detailed explanation. Looking forward to your early reply.

**Comment by RunpeiDong** [comment]
Hi @XqZeppelinhead0702,

We follow Flamingo to use COCO `Karpathy` splits for evaluation sets (5000). Please read Section B.1.4 of Flamingo paper. Also, you can use the files that we have processed as [here](https://drive.google.com/drive/folders/1olTmjeOmFTtD9Z5GXKSDOsh7eWElCtbr) if you are using omni eval system to evaluate.

The `Karpathy` split can be downloaded from [huggingface](https://huggingface.co/datasets/yerevann/coco-karpathy).

**Comment by XqZeppelinhead0702** [comment]
> Hi @XqZeppelinhead0702,
> 
> We follow Flamingo to use COCO `Karpathy` splits for evaluation sets (5000). Please read Section B.1.4 of Flamingo paper. Also, you can use the files that we have processed as [here](https://drive.google.com/drive/folders/1olTmjeOmFTtD9Z5GXKSDOsh7eWElCtbr) if you are using omni eval system to evaluate.
> 
> The `Karpathy` split can be downloaded from [huggingface](https://huggingface.co/datasets/yerevann/coco-karpathy).

Thanks a lot for providing these resources. I'll check out them carefully.
