### ISSUE TITLE
Will DPO code be released?

### ISSUE THREAD

**Issue by JuanJia** [RunpeiDong/DreamLLM#26]
Thanks for your wonderful work, will the DPO code be released?

**Comment by RunpeiDong** [comment]
Hi @JuanJia,

We didn't use DPO training on DreamLLM. Are you talking about direct preference optimization, just to confirm?

**Comment by JuanJia** [comment]
Yes, direct preference optimization. Just want to try some DPO on your work, so request for some reference.

**Comment by RunpeiDong** [comment]
Hi @JuanJia,

The multimodal comprehension part is the same as other MLLMs, so you can directly apply DPO by loading the dreamllm model and training it.
