### ISSUE TITLE
How to generate interleaved content creation examples shown in Fig 3 of the paper

### ISSUE THREAD

**Issue by chenwei746** [RunpeiDong/DreamLLM#9]
Hi, I noticed that the examples in inference.py only use captions to generate images. How can I use dreamllm to generate interleaved content creation examples shown in Fig 3 of the paper? Thank you very much!

**Comment by RunpeiDong** [comment]
Hi @chenwei746,

Thank you for your question! This can be implemented by writing a script of free-form multimodal dialogue. Compared to text-only dialogue, you only need to deal with image generation by detecting dream token <dream_start>. Whenever one such special token is generated, you should apply a diffusion pipeline based on history contexts, which is very similar to the provided image generation script. 

I will upload one cleaned code example when I have time. I have recently been very busy, and I do not have any GPU resources to use.

**Comment by RunpeiDong** [comment]
Hi,
Please refer to https://github.com/RunpeiDong/DreamLLM/issues/15#issuecomment-2255676747

**Comment by chenwei746** [comment]
Thank you very much!
